apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: secret-policy-operator-secret.validator
  annotations:
    cert-manager.io/inject-ca-from: secret-policy-operator-system/secret-policy-operator-serving-cert
webhooks:
  - name: secret.validator.kishore.dev
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    clientConfig:
      service:
        namespace: secret-policy-operator-system
        name: secret-policy-operator-webhook-service
        path: /validate-v1-secret
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["secrets"]
