apiVersion: compliance.security.local/v1alpha1
kind: SecretPolicy
metadata:
  labels:
    app.kubernetes.io/name: secret-policy-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretpolicy-sample
spec:
  # TODO(user): Add fields here
